<a href="https://colab.research.google.com/github/Ash-pixi/ML_ZTM/blob/main/pra_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series(["BMW", "Toyota", "lamborgini"])
series

0           BMW
1        Toyota
2    lamborgini
dtype: object

In [ ]:
color = pd.Series(["red", "blue","pink"])
color

0     red
1    blue
2    pink
dtype: object

In [ ]:
#data frame in 2 dimentions
car_data = pd.DataFrame({"make_car": series, "car_color":color})
car_data

     make_car car_color
0         BMW       red
1      Toyota      blue
2  lamborgini      pink

In [ ]:
from google.colab import files
uploaded = files.upload()
file_read = pd.read_csv("car_sales.csv")
file_read

Saving file2.csv to file2.csv

FileNotFoundError: [Errno 2] No such file or directory: 'car_sales.csv'

In [ ]:
file_read.dtypes

In [ ]:
file_read.index

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [ ]:
a1

In [ ]:
a1.size

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()
heart_disease = pd.read_csv("file2.csv")

Saving file2.csv to file2 (1).csv

In [ ]:
heart_disease

,age,sex,chest_pain_type,resting_bp,cholesterol,fasting_bs,rest_ecg,max_hr,exercise_angina,oldpeak,st_slope,heart_disease
0,63,1,3,145,233,1,0,150,0,2.3,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,1
2,41,0,1,130,204,0,0,172,0,1.4,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,1
7,44,1,1,120,263,0,1,173,0,0.0,2,1
8,52,1,2,172,199,1,1,162,0,0.5,2,1
9,57,1,2,150,168,0,1,174,0,1.6,2,1
10,54,1,0,140,239,0,1,160,0,1.2,2,0
11,48,0,2,130,275,0,1,139,0,0.2,2,0
12,49,1,1,130,266,0,1,171,0,0.6,2,0
13,64,1,3,110,211,0,0,144,1,1.8,1,0
14,58,0,2,150,283,1,0,162,0,1.0,2,0

In [ ]:
x = heart_disease.drop("heart_disease", axis=1)

y = heart_disease["heart_disease"]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [ ]:
clf.fit(x_train, y_train);
    `