<a href="https://colab.research.google.com/github/Ash-pixi/ML_ZTM/blob/main/sciketLearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np

In [71]:
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import pandas as pd

In [1]:
from google.colab import files
uploaded = files.upload()

Saving heart_disease.csv to heart_disease.csv

In [5]:
heart_disease = pd.read_csv("heart_disease.csv")

In [6]:
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,67,1,2,123,263,0,0,195,0,1.2,0,0,2,0
1,57,0,2,139,329,0,0,146,0,3.6,2,0,2,1
2,43,1,1,113,210,0,1,174,0,1.6,0,0,2,0
3,71,0,0,127,188,0,0,127,1,0.0,2,0,2,1
4,36,0,1,131,164,0,1,163,0,1.8,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,70,0,3,135,246,0,2,143,0,2.0,0,2,2,1
196,72,1,3,141,287,1,1,155,0,2.2,1,0,1,1
197,52,1,1,116,221,0,1,157,1,3.6,1,0,3,1
198,43,1,2,143,249,1,0,135,1,1.6,0,1,3,1
199,60,1,3,150,224,0,1,171,0,1.3,1,2,2,1

In [9]:
x = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

In [7]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [12]:
clf.fit(x_train, y_train);

In [14]:
y_label = clf.predict(np.array([0,2,3,4]))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [15]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
74,42,1,0,176,287,0,1,112,0,2.9,2,1,3
130,63,0,0,120,291,0,1,148,0,0.0,1,0,2
34,43,1,0,104,186,0,0,176,0,0.0,1,1,2
15,31,1,2,131,255,0,0,148,0,1.4,0,2,2
37,31,1,1,129,320,0,0,165,0,2.3,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,46,1,0,107,229,0,0,166,0,2.2,2,1,1
123,52,1,0,130,260,0,1,147,0,1.0,1,0,2
187,31,1,2,122,254,0,1,102,0,0.0,1,0,2
8,51,1,0,106,257,0,1,145,0,0.9,1,2,1
150,67,1,0,135,202,0,2,106,0,0.4,2,0,2

In [16]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
119,62,1,1,138,278,0,1,156,0,0.0,1,0,2
71,62,1,0,126,209,1,1,148,0,0.0,2,0,2
58,42,1,0,119,243,1,0,95,0,0.0,0,2,2
199,60,1,3,150,224,0,1,171,0,1.3,1,2,2
131,29,0,2,130,266,0,1,206,0,1.1,2,0,2
43,46,1,0,115,242,0,0,150,0,3.0,1,1,2
48,54,1,2,115,232,0,1,128,1,1.8,1,0,2
134,75,0,0,145,319,0,1,186,0,1.2,0,0,2
45,53,1,1,114,276,0,2,118,0,2.2,1,2,3
176,48,1,3,135,252,0,1,154,1,1.1,1,0,2
168,30,0,1,134,273,0,0,174,1,1.1,2,0,2
147,70,1,1,127,184,0,1,115,1,0.3,0,0,2
92,57,0,0,114,259,0,2,114,0,0.4,1,0,2
173,56,1,2,141,233,0,0,153,0,2.1,1,2,2
103,52,1,0,117,323,0,1,150,1,1.4,1,0,2
46,42,0,1,129,328,0,0,185,0,2.0,0,2,2
5,49,1,1,137,312,0,0,126,1,1.4,1,0,2
159,43,1,0,125,240,0,0,151,0,0.0,0,0,2
21,66,0,1,150,221,0,0,124,0,1.0,1,0,2
84,73,1,2,155,276,0,1,128,0,1.5,2,0,2
167,56,1,2,155,219,0,1,177,0,2.1,1,3,1
169,70,0,0,126,288,0,0,163,0,0.0,1,0,3
26,50,1,1,112,168,0,0,148,0,0.1,1,0,1
163,41,1,3,114,324,1,1,118,0,4.2,1,0,2
67,57,0,2,95,151,0,1,168,0,2.9,0,0,2
113,69,0,0,115,251,1,0,177,0,0.7,0,0,2
152,60,1,3,122,267,0,1,177,1,0.5,1,0,2
55,36,0,1,112,238,0,0,199,0,2.0,2,0,3
193,65,1,2,115,275,0,2,147,1,1.4,0,3,2
158,73,1,1,143,360,0,0,162,1,0.7,0,0,3
54,72,1,3,121,253,0,0,134,0,1.7,1,0,3
39,35,1,0,128,177,0,1,180,1,3.6,2,0,2
156,51,0,0,134,219,0,2,134,0,1.3,1,1,1
140,42,0,0,92,268,0,1,137,0,1.4,2,0,2
88,54,1,0,131,196,1,0,152,0,1.0,0,0,2
121,76,0,1,102,236,0,1,159,0,0.0,1,1,3
16,50,1,1,160,209,1,1,154,0,0.0,2,1,3
102,36,1,2,121,187,0,2,151,0,0.8,0,0,3
85,46,1,2,143,264,1,1,145,1,0.5,1,0,3
60,64,0,2,128,212,0,1,119,0,0.3,1,0,2

In [17]:
y_preds = clf.predict(x_test)
y_preds

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1])

In [18]:
y_test

119    0
71     1
58     1
199    1
131    0
43     1
48     0
134    1
45     1
176    0
168    0
147    1
92     1
173    1
103    1
46     0
5      1
159    0
21     0
84     0
167    1
169    1
26     0
163    1
67     0
113    1
152    0
55     0
193    1
158    1
54     0
39     1
156    0
140    1
88     1
121    1
16     1
102    0
85     1
60     1
Name: target, dtype: int64

In [19]:
clf.score(x_train,y_train)

1.0

In [20]:
clf.score(x_test,y_test)

0.675

In [21]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.67      0.38      0.48        16
           1       0.68      0.88      0.76        24

    accuracy                           0.68        40
   macro avg       0.67      0.62      0.62        40
weighted avg       0.67      0.68      0.65        40

In [22]:
confusion_matrix(y_test, y_preds)

array([[ 6, 10],
       [ 3, 21]])

In [23]:
accuracy_score(y_test, y_preds)

0.675

In [25]:
np.random.seed(42)
for i in range(10,100,10):
  print(f"Trying model with {i} estimators...")
  clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
  print(f"Model accuracy on test set: {clf.score(x_test,y_test)* 100:.2f}%")
  print("")

Trying model with 10 estimators...
Model accuracy on test set: 57.50%

Trying model with 20 estimators...
Model accuracy on test set: 65.00%

Trying model with 30 estimators...
Model accuracy on test set: 57.50%

Trying model with 40 estimators...
Model accuracy on test set: 65.00%

Trying model with 50 estimators...
Model accuracy on test set: 60.00%

Trying model with 60 estimators...
Model accuracy on test set: 65.00%

Trying model with 70 estimators...
Model accuracy on test set: 70.00%

Trying model with 80 estimators...
Model accuracy on test set: 65.00%

Trying model with 90 estimators...
Model accuracy on test set: 60.00%

In [26]:
import joblib

joblib.dump(clf, "random_forest_model.pkl")

['random_forest_model.pkl']

In [27]:
from google.colab import files
files.download("random_forest_model.pkl")

In [62]:
from google.colab import files
uploaded = files.upload()

Saving car_sales.csv to car_sales.csv

In [32]:
import joblib

load_model = joblib.load("random_forest_model.pkl")

In [33]:
load_model.score(x_test,y_test)

0.6

In [37]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,67,1,2,123,263,0,0,195,0,1.2,0,0,2,0
1,57,0,2,139,329,0,0,146,0,3.6,2,0,2,1
2,43,1,1,113,210,0,1,174,0,1.6,0,0,2,0
3,71,0,0,127,188,0,0,127,1,0.0,2,0,2,1
4,36,0,1,131,164,0,1,163,0,1.8,2,1,2,1

In [38]:
x = heart_disease.drop("target",axis=1)
x.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,67,1,2,123,263,0,0,195,0,1.2,0,0,2
1,57,0,2,139,329,0,0,146,0,3.6,2,0,2
2,43,1,1,113,210,0,1,174,0,1.6,0,0,2
3,71,0,0,127,188,0,0,127,1,0.0,2,0,2
4,36,0,1,131,164,0,1,163,0,1.8,2,1,2

In [39]:
y = heart_disease["target"]
y.head()

0    0
1    1
2    0
3    1
4    1
Name: target, dtype: int64

In [40]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [41]:
x_test.shape, x_train.shape, y_test.shape, y_train.shape

((40, 13), (160, 13), (40,), (160,))

In [ ]:
##

In [63]:
from google.colab import files
uploaded = files.upload()

Saving car_sales.csv to car_sales (1).csv

In [64]:
car_sale = pd.read_csv('car_sales.csv')
car_sale

,Car_ID,Brand,Model_Year,Mileage,Fuel_Type,Engine_Size,Horsepower,Transmission,Previous_Owners,Price
0,1,Toyota,2018,45000,Petrol,1.8,140,Automatic,1,18500
1,2,Honda,2020,22000,Hybrid,1.5,121,CVT,1,24000
2,3,Ford,2015,85000,Diesel,2.0,150,Manual,3,10500
3,4,BMW,2021,12000,Petrol,3.0,335,Automatic,1,48000
4,5,Hyundai,2017,60000,Petrol,1.6,128,Manual,2,13200
5,6,Tesla,2022,5000,Electric,0.0,450,Automatic,1,55000
6,7,Audi,2019,35000,Diesel,2.0,190,Automatic,1,29000
7,8,Nissan,2016,72000,Petrol,1.2,109,Manual,2,9800
8,9,Chevrolet,2014,95000,Petrol,2.5,196,Automatic,4,8500
9,10,Mercedes,2023,1500,Hybrid,2.0,255,Automatic,1,62000
10,11,Volkswagen,2018,52000,Diesel,1.6,115,Manual,2,16700
11,12,Kia,2021,18000,Petrol,1.6,177,Automatic,1,22500

In [65]:
len(car_sale)

12

In [66]:
car_sale.dtypes

Car_ID               int64
Brand               object
Model_Year           int64
Mileage              int64
Fuel_Type           object
Engine_Size        float64
Horsepower           int64
Transmission        object
Previous_Owners      int64
Price                int64
dtype: object

In [72]:
x = car_sale.drop("Price",axis=1)
y = car_sale["Price"]
x = pd.get_dummies(x, drop_first=True)

In [73]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [76]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train,y_train)
print(f"Model score on the test set: {model.score(x_test,y_test) * 100:.2f}%")

Model score on the test set: 34.66%